import { createContext, useContext, useEffect, useState } from "react";
import { api } from "../services/api";
import { useAuth } from "./AuthContext";

export const SUPPORTED_LANGUAGES = [
  { value: "fr", label: "Français" },
  { value: "en", label: "English" },
];

const DEFAULT_LANGUAGE = "fr";
const LanguageContext = createContext(null);

const TRANSLATIONS = {
  fr: {
    appName: "Suivi Employés",
    workspace: "Espace de travail",
    account: "Compte",
    dashboard: "Tableau de bord",
    attendance: "Présence",
    tasks: "Tâches",
    activity: "Activité",
    history: "Historique",
    employees: "Employés",
    teams: "Équipes",
    profile: "Mon profil",
    settings: "Paramètres",
    reports: "Rapports",
    home: "Accueil",
    more: "Plus",
    close: "Fermer",
    quickAccess: "Accès rapides",
    expand: "Étendre",
    collapse: "Réduire",
    mainNavigation: "Navigation principale",
    logout: "Se déconnecter",
    back: "Retour",
    personalSettings: "Paramètres personnels",
    personalization: "Personnalisation",
    personalSettingsDescription: "Ces préférences ne s’appliquent qu’à votre compte.",
    language: "Langue",
    languageDescription: "Choisissez la langue de votre interface.",
    colors: "Couleurs",
    colorsDescription: "Choisissez une interface adaptée à votre usage.",
    font: "Police",
    fontDescription: "Utilisée uniquement par votre compte.",
    preview: "Aperçu",
    save: "Enregistrer",
    saved: "Modifications enregistrées.",
    saveError: "Impossible d’enregistrer les préférences.",
    performanceAnalysis: "Analyse de performance",
    hello: "Bonjour",
    you: "à vous",
    followActivity: "Suivez visuellement votre activité.",
    companyActivity: "Une lecture graphique de l’activité de l’entreprise.",
    lastDays: "30 derniers jours",
    lastMonths3: "3 derniers mois",
    lastMonths6: "6 derniers mois",
    lastMonths12: "12 derniers mois",
    completed: "Réalisées",
    toProcess: "À traiter",
    overallRate: "Taux global",
    myActivity: "Mon activité",
    activityEvolution: "Évolution de l’activité",
    createdVsCompleted: "Comparaison entre les tâches créées et les tâches réalisées.",
    statusBreakdown: "Répartition des statuts",
    periodSummary: "Vue synthétique des tâches de la période.",
    averageProductivity: "Productivité moyenne",
    completionRate: "Taux de réalisation",
    recentActivity: "Activité récente",
    noData: "Pas encore de données.",
    attendanceDescription: "Pointez votre arrivée et votre départ.",
    clockIn: "Pointer l’arrivée",
    clockOut: "Pointer le départ",
    superAdminAttendance: "Le super administrateur ne pointe pas ses arrivées/départs. Il reçoit toutefois le rapport de présence de son équipe.",
    attendanceReport: "Rapport de présence / absence",
    employee: "Employé",
    role: "Rôle",
    status: "Statut",
    arrival: "Arrivée",
    departure: "Départ",
    date: "Date",
    noAttendance: "Aucun pointage pour le moment.",
    employeesDescription: "Créez un accès pour chaque employé : il se connectera avec son matricule et le code que vous lui remettez.",
    employeeId: "Matricule",
    fullName: "Nom complet",
    passwordCode: "Code (mot de passe)",
    manager: "Manager",
    department: "Département",
    position: "Poste",
    none: "Aucune",
    createAccess: "Créer l’accès",
    noEmployees: "Aucun employé pour le moment.",
    teamsAndDepartments: "Équipes et départements",
    teamsDescription: "Gérez les équipes, les départements et les retards éventuels sur les livrables.",
    teamName: "Nom de l’équipe",
    teamMembers: "Membres de l’équipe",
    leader: "Responsable",
    changeLeader: "Changer le responsable",
    chooseLeader: "Choisir un responsable",
    createTeam: "Créer l’équipe",
    deadlineAlert: "Alerte d’échéance",
    noOverdueTeams: "Aucune équipe en retard pour le moment.",
    viewMembers: "Voir les membres",
    noTeams: "Aucune équipe pour le moment.",
    all: "Toutes",
    done: "Faites",
    todo: "À faire",
    inProgress: "En cours",
    inReview: "En révision",
    rejected: "Rejetées",
    cancelled: "Annulées",
    historyReserved: "Cette page est réservée aux employés.",
    historyDateDescription: "Toutes les tâches créées à cette date, triées par statut.",
    backToHistory: "Retour à l’historique",
    taskDetails: "Détails de la tâche",
    noTasksDate: "Aucune tâche pour cette date.",
    historyDescription: "Cliquez sur une date pour voir toutes les tâches créées ce jour-là.",
    tasksRecorded: "tâche(s) enregistrée(s)",
    noHistory: "Aucun historique pour le moment.",
    add: "Ajouter",
    create: "Créer",
    edit: "Modifier",
    validate: "Valider",
    addTask: "Ajouter une tâche",
    editTask: "Modifier la tâche",
    taskDescription: "Ajoutez les tâches que vous avez réalisées pendant la journée.",
    noTasks: "Aucune tâche pour le moment.",
    createTask: "Créer une tâche",
    assignTask: "Attribuer la tâche",
    manageTasks: "Gérez les tâches, l’ordre et les statuts de votre équipe.",
    title: "Titre",
    description: "Description",
    employeeChoice: "Choisir un employé",
    priority: "Priorité",
    project: "Projet",
    withoutProject: "Sans projet",
    noDescription: "Aucune description.",
    selectEmployeeTasks: "Cliquez sur le profil d’un employé pour voir ses tâches et son historique.",
    createTaskForEmployee: "Créer une tâche pour un employé",
    noEmployeesFound: "Aucun employé trouvé.",
    assignedTo: "Assigné à",
    login: "Se connecter",
    administration: "Administration",
    employeeIdLogin: "Matricule ou code incorrect.",
    invalidCredentials: "Identifiants incorrects.",
    registerCompany: "Créer mon entreprise",
    noAccount: "Pas encore de compte ?",
    createCompany: "Créer mon entreprise",
    yourName: "Votre nom",
    alreadyAccount: "Déjà un compte ?",
    profiles: "Profils",
    profileDescription: "Consultez votre profil et les informations de votre entreprise.",
    name: "Nom",
    company: "Entreprise",
    companyProfile: "Profil entreprise",
    superAdminEdit: "Vous êtes SUPER_ADMIN : vous pouvez modifier ces informations.",
    viewOnly: "Consultation uniquement. Seul le SUPER_ADMIN peut modifier ces informations.",
    updatedProfile: "Profil entreprise mis à jour.",
    dataAnalysis: "Analyse de données",
    activityReports: "Rapports d’activité",
    reportsDescription: "Conservez une photographie fiable des performances de l’entreprise.",
    thisMonth: "Ce mois",
    threeMonths: "3 mois",
    sixMonths: "6 mois",
    oneYear: "1 an",
    generate: "Générer",
    reportFor: "Rapport sur",
    generatedOn: "Généré le",
    downloadPdf: "Télécharger le PDF",
    noReports: "Aucun rapport enregistré",
    days: "jours",
    choosePeriodGenerate: "Choisissez une période puis cliquez sur Générer.",
    employeeRatio: "Votre ratio de tâches terminées par rapport aux tâches créées.",
    completionPercent: "Pourcentage de tâches terminées par intervalle.",
    employeeAverage: "Moyenne des taux de réalisation de tous les employés.",
    teamProductivity: "Productivité des équipes",
    teamTasksOnly: "Seules les tâches attribuées dans le cadre d’une équipe sont comptées ici.",
    activeEmployees: "Employés actifs",
    overdueTasks: "Tâches en retard",
    created: "Créées",
    completedPlural: "Réalisées",
    realization: "Réalisation",
    remaining: "Restantes",
    recentTasksDescription: "Vos dernières tâches de la période.",
    noActivity: "Aucune activité sur cette période.",
    statisticalChart: "Courbe statistique",
    value: "Valeur",
    byDay: "Par jour",
    byWeek: "Par semaine",
    yesterday: "Hier",
    last7Days: "7 derniers jours",
    today: "Aujourd’hui",
    password: "Mot de passe",
    registerDescription: "Ce compte administrateur pourra ensuite ajouter vos employés.",
    yourCompany: "Votre entreprise",
    lastStep: "Dernière étape avant d’ajouter vos employés.",
    companyName: "Nom de l’entreprise",
    address: "Adresse",
    phone: "Téléphone",
  },
  en: {
    appName: "Employee Tracker",
    workspace: "Workspace",
    account: "Account",
    dashboard: "Dashboard",
    attendance: "Attendance",
    tasks: "Tasks",
    activity: "Activity",
    history: "History",
    employees: "Employees",
    teams: "Teams",
    profile: "My profile",
    settings: "Settings",
    reports: "Reports",
    home: "Home",
    more: "More",
    close: "Close",
    quickAccess: "Quick access",
    expand: "Expand",
    collapse: "Collapse",
    mainNavigation: "Main navigation",
    logout: "Sign out",
    back: "Back",
    personalSettings: "Personal settings",
    personalization: "Personalization",
    personalSettingsDescription: "These preferences apply only to your account.",
    language: "Language",
    languageDescription: "Choose your interface language.",
    colors: "Colors",
    colorsDescription: "Choose an interface that fits your workflow.",
    font: "Font",
    fontDescription: "Used only for your account.",
    preview: "Preview",
    save: "Save",
    saved: "Changes saved.",
    saveError: "Unable to save preferences.",
    performanceAnalysis: "Performance analysis",
    hello: "Hello",
    you: "there",
    followActivity: "Track your activity visually.",
    companyActivity: "A graphical view of company activity.",
    lastDays: "Last 30 days",
    lastMonths3: "Last 3 months",
    lastMonths6: "Last 6 months",
    lastMonths12: "Last 12 months",
    completed: "Completed",
    toProcess: "To process",
    overallRate: "Overall rate",
    myActivity: "My activity",
    activityEvolution: "Activity over time",
    createdVsCompleted: "Comparison between created and completed tasks.",
    statusBreakdown: "Status breakdown",
    periodSummary: "Summary of tasks for the period.",
    averageProductivity: "Average productivity",
    completionRate: "Completion rate",
    recentActivity: "Recent activity",
    noData: "No data yet.",
    attendanceDescription: "Clock in and out for your workday.",
    clockIn: "Clock in",
    clockOut: "Clock out",
    superAdminAttendance: "Super administrators do not clock in or out. They can still view their team attendance report.",
    attendanceReport: "Attendance / absence report",
    employee: "Employee",
    role: "Role",
    status: "Status",
    arrival: "Clock in",
    departure: "Clock out",
    date: "Date",
    noAttendance: "No attendance record yet.",
    employeesDescription: "Create access for each employee: they will sign in with their employee ID and the code you provide.",
    employeeId: "Employee ID",
    fullName: "Full name",
    passwordCode: "Code (password)",
    manager: "Manager",
    department: "Department",
    position: "Position",
    none: "None",
    createAccess: "Create access",
    noEmployees: "No employees yet.",
    teamsAndDepartments: "Teams and departments",
    teamsDescription: "Manage teams, departments, and potential delivery delays.",
    teamName: "Team name",
    teamMembers: "Team members",
    leader: "Leader",
    changeLeader: "Change leader",
    chooseLeader: "Choose a leader",
    createTeam: "Create team",
    deadlineAlert: "Deadline alert",
    noOverdueTeams: "No overdue teams at the moment.",
    viewMembers: "View members",
    noTeams: "No teams yet.",
    all: "All",
    done: "Completed",
    todo: "To do",
    inProgress: "In progress",
    inReview: "In review",
    rejected: "Rejected",
    cancelled: "Cancelled",
    historyReserved: "This page is reserved for employees.",
    historyDateDescription: "All tasks created on this date, sorted by status.",
    backToHistory: "Back to history",
    taskDetails: "Task details",
    noTasksDate: "No tasks for this date.",
    historyDescription: "Select a date to view all tasks created that day.",
    tasksRecorded: "task(s) recorded",
    noHistory: "No history yet.",
    add: "Add",
    create: "Create",
    edit: "Edit",
    validate: "Complete",
    addTask: "Add a task",
    editTask: "Edit task",
    taskDescription: "Add the tasks you completed during the day.",
    noTasks: "No tasks yet.",
    createTask: "Create a task",
    assignTask: "Assign task",
    manageTasks: "Manage your team’s tasks, order, and statuses.",
    title: "Title",
    description: "Description",
    employeeChoice: "Choose an employee",
    priority: "Priority",
    project: "Project",
    withoutProject: "No project",
    noDescription: "No description.",
    selectEmployeeTasks: "Select an employee profile to view their tasks and history.",
    createTaskForEmployee: "Create a task for an employee",
    noEmployeesFound: "No employees found.",
    assignedTo: "Assigned to",
    login: "Sign in",
    administration: "Administration",
    employeeIdLogin: "Incorrect employee ID or code.",
    invalidCredentials: "Incorrect credentials.",
    registerCompany: "Create my company",
    noAccount: "No account yet?",
    createCompany: "Create my company",
    yourName: "Your name",
    alreadyAccount: "Already have an account?",
    profiles: "Profiles",
    profileDescription: "View your profile and your company information.",
    name: "Name",
    company: "Company",
    companyProfile: "Company profile",
    superAdminEdit: "You are a SUPER_ADMIN: you can edit this information.",
    viewOnly: "View only. Only the SUPER_ADMIN can edit this information.",
    updatedProfile: "Company profile updated.",
    dataAnalysis: "Data analysis",
    activityReports: "Activity reports",
    reportsDescription: "Keep a reliable snapshot of company performance.",
    thisMonth: "This month",
    threeMonths: "3 months",
    sixMonths: "6 months",
    oneYear: "1 year",
    generate: "Generate",
    reportFor: "Report for",
    generatedOn: "Generated on",
    downloadPdf: "Download PDF",
    noReports: "No reports saved",
    days: "days",
    choosePeriodGenerate: "Choose a period, then click Generate.",
    employeeRatio: "Your ratio of completed to created tasks.",
    completionPercent: "Percentage of tasks completed over time.",
    employeeAverage: "Average completion rate across all employees.",
    teamProductivity: "Team productivity",
    teamTasksOnly: "Only tasks assigned within a team are counted here.",
    activeEmployees: "Active employees",
    overdueTasks: "Overdue tasks",
    created: "Created",
    completedPlural: "Completed",
    realization: "Completion",
    remaining: "Remaining",
    recentTasksDescription: "Your latest tasks for the period.",
    noActivity: "No activity during this period.",
    statisticalChart: "Statistical chart",
    value: "Value",
    byDay: "By day",
    byWeek: "By week",
    yesterday: "Yesterday",
    last7Days: "Last 7 days",
    today: "Today",
    password: "Password",
    registerDescription: "This administrator account can add employees next.",
    yourCompany: "Your company",
    lastStep: "One last step before adding your employees.",
    companyName: "Company name",
    address: "Address",
    phone: "Phone",
  },
};

function normalizeLanguage(language) {
  return language === "en" ? "en" : DEFAULT_LANGUAGE;
}

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(DEFAULT_LANGUAGE);
  const { firebaseUser } = useAuth();

  useEffect(() => {
    let active = true;
    if (!firebaseUser) {
      setLanguageState(DEFAULT_LANGUAGE);
      return undefined;
    }
    api.get("/settings").then((data) => {
      if (active) setLanguageState(normalizeLanguage(data.language));
    }).catch(() => {});
    return () => { active = false; };
  }, [firebaseUser]);

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  async function saveLanguage(nextLanguage) {
    const next = normalizeLanguage(nextLanguage);
    await api.patch("/settings", { language: next });
    setLanguageState(next);
    return next;
  }

  function t(key) {
    return TRANSLATIONS[language][key] || TRANSLATIONS[DEFAULT_LANGUAGE][key] || key;
  }

  return <LanguageContext.Provider value={{ language, setLanguage: setLanguageState, saveLanguage, t }}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
